cask_args appdir: '/Applications'

tap "hashicorp/tap"
tap "daipeihust/tap"
brew "coreutils"
brew "perl"
brew "autoconf"
brew "automake"
brew "openssl@3"
brew "gnupg"
brew "readline"
brew "cmake"
brew "curl"
brew "wget"
brew "ack"
brew "gawk"
brew "fzf"
brew "tree"
brew "gh"
brew "git"
brew "git-lfs"
brew "htop"
brew "jq"
brew "yq"
brew "kustomize"
brew "helm"
brew "mas"
brew "cobra-cli"
brew "protobuf"
brew "neovim"

cask "ghostty"
cask "aws-vault-binary"
cask "font-fira-code"
cask "google-chrome"
cask "hammerspoon"
cask "stats"
cask "orbstack"
cask "tableplus"
cask "visual-studio-code"
cask "antigravity"
cask "rustdesk"
cask "spotify"
cask "slack"
cask "wechat"
cask "appcleaner"

mas "Dictionaries", id: 1380563956
mas "LINE", id: 539883307
mas "Xcode", id: 497799835
